### ISSUE TITLE
Confusion with timing

### ISSUE THREAD

**Issue by pecey** [ataitler/RDDL-demo-agent#8]
Hi,

In `main.py`, line 74 says : `timed_out = False if init_timed_out==False else True` and `init_timed_out` is set to True when the agent exhausts the initial one hour budget.  Doesn't it mean that if you exhaust one hour, the defaultAgent gets triggered by default? Whereas according to my understanding, the time allocation for the agent to execute actions is 1 hour + 4 min/trial.

Am I missing something here?

**Comment by ataitler** [comment]
You are right. if the init time of 1 hour is exceeded, the agent should still get the change to interact with the environment for the 4 minutes per trial it deserves.

It is now fixed. The 4 minutes per trial will be allocated regardless if the agent finished the initialization in the designated 60 minutes.
Note that the boolean flag `init_timed_out` is still present, in case one wishes to inquire whether was a time out during initialization.
